Feature/homeworks
cleannetcode/CleannetCode_bot pull request #6
Opened 2023-02-10 19:33 UTC by oqqA

Че происходит по шагам:
1. забирает сообщения из дискуссий (в конфиге можно указать несколько)
2. сверяется с кешом, отличия считаются новыми сообщениями, по пути вытаскивает ссылки
3. новые сообщения отправляются в телеграм канал
4. по ссылкам отслеживаем изменения по репозеториям
5. обновления отпрвляются в телеграм

- конфиги в одной секции "HomeworksServiceOptions"
- запуск по таймеру "CheckTimerInMinutes" : 120 минут, то есть раз в 2 часа

todo:
- и не знаю как будут сообщения в канале телеграмма выглядеть, и нужено будет 2 разных канала или один?
- наверное нужно игнорировать некоторые ссылки
- остался небольшой рефакторинг для одной фукнкции (медленно работает), под вечер устал.. оставил комментарии c todo. В как раз после стрима комплекстно отрефакторю))

вот так выклядит кеш если что:

{
  "DiscussionsData": {
    "https://github.com/cleannetcode/Index/discussions/32": {
      "Messages": [
        {
          "Author": "ShamanValius",
          "Message": "\n        Сделанное немного по своему код из стрима\nАлгоритмы пока не делал.\n    ",
          "DatetimeCreateNode": "2022-11-13T17:52:18+00:00"
        },
        {
          "Author": "nikysn",
          "Message": "\n        LeetCode_ : https://github.com/nikysn/LeetCode\nPlayerDataBase :  https://github.com/nikysn/ToDoList-PlayerDataBase\nПока еще думаю какой проект начать делать\n    ",
          "DatetimeCreateNode": "2023-01-02T13:35:11+00:00"
        }
      ],
      "Links": [
        {
          "Link": "https://github.com/8981/LeetCode",
          "LastCommit": "added medium task Group Anagrams",
          "LastGithubUpdate": "2022-11-11T21:12:27+00:00"
        }
        {
          "Link": "https://github.com/SamirKurbatov/Barncale",
          "LastCommit": "initCommit",
          "LastGithubUpdate": "2022-11-03T11:09:54+00:00"
        }
      ]
    }
  }
}

2023-02-11 15:11 UTC, Alex2021cyberhuman requested changes

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/DiscussionMessages.cs
> +public record DiscussionMessages
Не использован сокращенный синтаксис определения record

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksCache.cs
> +}
Несколько классов в файле

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +    }
this там где не надо

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +        this._discussionMessagesRepository = new GithubDataRepository(_config.FileNameCache ?? "cachedHomeworkMessages0.json");
Сокрытая зависимость - вынести в DI

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +        // var arrNewMessage = resultAllTasks.Cast<DiscussionMessages>().ToArray();
Закомментированный код

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +        // }
Закомментированный код

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +        // var tasks = new List<Task<LinkData>>();
Закомментированный код

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +    // и добавить tasks (а то долго) где находить обновленные репы через .Except
Закомментированный код

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksServiceOptions.cs
> +}
Несколько классов в файле

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksServiceOptions.cs
> +namespace CleannetCode_bot.Features.Homeworks;
file-scoped namespace

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/HomeworksHandler.cs
> +namespace CleannetCode_bot.Features.Homeworks;
file-scoped namespace

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/GithubDataRepository.cs
> +namespace CleannetCode_bot.Features.Homeworks;
file-scoped namespace

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/TimerHomeworksService.cs
> +namespace CleannetCode_bot.Features.Homeworks;
file-scoped namespace

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/Features/Homeworks/TimerHomeworksService.cs
> +            TimeSpan.FromMinutes(delay));
неправильное использование Timer

2023-02-11 15:11 UTC, Alex2021cyberhuman commented on CleannetCode_bot/CleannetCode_bot.csproj
> +    <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
Не рассмотрено решение через api гитхаб

2023-02-12 05:02 UTC, oqqA commented
ревью на стриме https://www.youtube.com/watch?v=Dv3YGL0i1q8

2023-02-12 05:02 UTC, closed without merging

2023-02-12 06:39 UTC, Alex2021cyberhuman commented
А что закрыл?